### ISSUE TITLE
Without an active shader, CC: Tweaked monitors are very dark

### ISSUE THREAD

**Issue by kjfitzpat** [coryjreid/logicraft#19]
Please see this issue on Iris Shaders Github that may be directly related: https://github.com/IrisShaders/Iris/issues/2053

if no shaders are enabled, monitors are VERY dark. The second any shader is enabled, the monitor becomes readable. I have tested several different shaders and this seems like a possible workaround.

With shader:
![image](https://github.com/coryjreid/logicraft/assets/921526/c8542696-5c44-4072-a98a-8aa5c7da043d)

Without shader:
![image](https://github.com/coryjreid/logicraft/assets/921526/bc21b672-ccd6-44ac-be03-52714e451a0c)

Workaround in mind, I have tested a few low-impact shaders to see if we could push those as the default people use, but so far a large number of them have really annoying issues with things like the Create mod or are just not well-maintained - go figure, a shader that does nothing is not up to par. List of low-impact shaders I tried so far:
- https://modrinth.com/shader/cyanide-shaders/version/1.1
- https://modrinth.com/shader/noshader

That being said, there are a few good reasons not to consider shaders are a feasible workaround:
- Shaders WILL impact performance
- Shaders are not universally compatible with all things in our mod pack (Twighlight forest auras not showing, for example)
- Shaders will screw with resource packs (the rainbow cursor not showing up when shaders are active is a good example)

**Comment by kjfitzpat** [comment]
I tried adding a resource pack to see if *by chance* that would make a difference but the results persist: https://modrinth.com/resourcepack/computercreate/gallery

![image](https://github.com/coryjreid/logicraft/assets/921526/a3902f6a-1b41-4ae4-9ff6-c45ecce9ba2c)

**Comment by coryjreid** [comment]
Research has indicated this is indeed an issue with the IrisShaders mod (and therefore, the port of this mod that we're using).

In testing we did find having Night Vision active alleviates the issue, which seems an acceptable workaround given the pack's endgame is designed to include the Mekasuit.
