### ISSUE TITLE
Remove Energetic Angel Ring Recipe

### ISSUE THREAD

**Issue by pkfreitag** [coryjreid/logicraft#21]
The ID is angelring:energetic_angel_ring

It is a recipe that is not needed because it is not used in any of the Angel Ring upgrades.  It is confusing because in JEI it lists Angel Ring>Energetic Angel Ring>Leadstone Angel Ring, etc.  Where the tiers for the Angel Ring upgrades are the following: Angel Ring>Leadstone Angel Ring>Hardened Angel Ring>Reinforced Angel Ring>Resonant Angel Ring.

**Comment by coryjreid** [comment]
f0c56b628550c0b3b2984760d738f2cd8f8c79b0
